use_frameworks!

platform :ios, '14.0'

target 'MLModulo_Example' do
  pod 'MLModulo', :path => '../'

  target 'MLModulo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
